const Data = [
  {
    id: 1,
    title: "item1",
    price: 150,
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas mollis ante et bibendum faucibus. Duis iaculis suscipit porta. Fusce commodo, felis sit amet ultrices vehicula, eros tellus vulputate turpis, sed consectetur libero dui tincidunt sem. Quisque mattis quam nisi, eget accumsan lectus finibus sed. Curabitur feugiat commodo elementum. Aliquam ac malesuada tortor, ut fermentum turpis. Cras posuere lacus eu blandit ultrices. Etiam eu finibus mi, eget viverra justo. Aenean ac neque et augue vestibulum eleifend sit amet eget turpis. Aenean eu nulla risus.Etiam ac scelerisque quam, et consequat urna. Nullam sit amet elementum justo. Cras fermentum luctus orci ac sollicitudin. Nulla semper tellus at leo finibus dictum. Vivamus tincidunt orci leo. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aenean aliquet, neque quis porta volutpat, augue nisi malesuada est, a porttitor libero elit sed turpis.Nunc ultricies sagittis tempus. Aliquam erat volutpat. Vestibulum pretium augue a eros tincidunt venenatis. Proin eu mauris mollis, vehicula purus id, venenatis sapien. Morbi in sagittis tortor. Ut laoreet, ex et rutrum posuere, est elit interdum nibh, quis finibus odio nibh at purus. Donec mattis, elit ac aliquet convallis, nibh lectus hendrerit lectus, in auctor nibh lectus at nunc. In ipsum nibh, pulvinar sit amet bibendum quis, facilisis in eros. Aliquam libero metus, faucibus nec ultrices vel, efficitur eget diam. Morbi ut urna malesuada, dapibus justo vitae, imperdiet est. Curabitur et odio a augue faucibus placerat et sit amet lectus. Ut tempor tellus at pharetra lacinia. Curabitur et leo ultrices, vestibulum odio in, malesuada diam. Proin ex ex, porttitor eget consectetur ac, pulvinar quis erat.Etiam id euismod metus. Quisque at diam arcu. Mauris semper porta erat id rutrum. Nunc sit amet felis sit amet dolor finibus venenatis. Mauris commodo quam nibh, sed euismod lectus egestas nec. Aliquam sit amet feugiat justo. Donec maximus placerat lectus et fringilla. Proin felis nibh, efficitur a lorem viverra, eleifend tempus nibh. Cras ac magna condimentum, dignissim felis eu, facilisis ante. Phasellus efficitur turpis et dolor imperdiet, vel gravida arcu sagittis. Vestibulum mollis ante eu eleifend aliquam. Etiam tincidunt viverra nisi id varius. Praesent non hendrerit turpis, id ultrices ligula. Nullam sed sapien mauris.",
    image: "/img/p5.png",
  },
  {
    id: 2,
    title: "item2",
    price: 220,
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas mollis ante et bibendum faucibus. Duis iaculis suscipit porta. Fusce commodo, felis sit amet ultrices vehicula, eros tellus vulputate turpis, sed consectetur libero dui tincidunt sem. Quisque mattis quam nisi, eget accumsan lectus finibus sed. Curabitur feugiat commodo elementum. Aliquam ac malesuada tortor, ut fermentum turpis. Cras posuere lacus eu blandit ultrices. Etiam eu finibus mi, eget viverra justo. Aenean ac neque et augue vestibulum eleifend sit amet eget turpis. Aenean eu nulla risus.Etiam ac scelerisque quam, et consequat urna. Nullam sit amet elementum justo. Cras fermentum luctus orci ac sollicitudin. Nulla semper tellus at leo finibus dictum. Vivamus tincidunt orci leo. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aenean aliquet, neque quis porta volutpat, augue nisi malesuada est, a porttitor libero elit sed turpis.Nunc ultricies sagittis tempus. Aliquam erat volutpat. Vestibulum pretium augue a eros tincidunt venenatis. Proin eu mauris mollis, vehicula purus id, venenatis sapien. Morbi in sagittis tortor. Ut laoreet, ex et rutrum posuere, est elit interdum nibh, quis finibus odio nibh at purus. Donec mattis, elit ac aliquet convallis, nibh lectus hendrerit lectus, in auctor nibh lectus at nunc. In ipsum nibh, pulvinar sit amet bibendum quis, facilisis in eros. Aliquam libero metus, faucibus nec ultrices vel, efficitur eget diam. Morbi ut urna malesuada, dapibus justo vitae, imperdiet est. Curabitur et odio a augue faucibus placerat et sit amet lectus. Ut tempor tellus at pharetra lacinia. Curabitur et leo ultrices, vestibulum odio in, malesuada diam. Proin ex ex, porttitor eget consectetur ac, pulvinar quis erat.Etiam id euismod metus. Quisque at diam arcu. Mauris semper porta erat id rutrum. Nunc sit amet felis sit amet dolor finibus venenatis. Mauris commodo quam nibh, sed euismod lectus egestas nec. Aliquam sit amet feugiat justo. Donec maximus placerat lectus et fringilla. Proin felis nibh, efficitur a lorem viverra, eleifend tempus nibh. Cras ac magna condimentum, dignissim felis eu, facilisis ante. Phasellus efficitur turpis et dolor imperdiet, vel gravida arcu sagittis. Vestibulum mollis ante eu eleifend aliquam. Etiam tincidunt viverra nisi id varius. Praesent non hendrerit turpis, id ultrices ligula. Nullam sed sapien mauris.",
    image: "/img/p6.png",
  },
  {
    id: 3,
    title: "item3",
    price: 930,
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas mollis ante et bibendum faucibus. Duis iaculis suscipit porta. Fusce commodo, felis sit amet ultrices vehicula, eros tellus vulputate turpis, sed consectetur libero dui tincidunt sem. Quisque mattis quam nisi, eget accumsan lectus finibus sed. Curabitur feugiat commodo elementum. Aliquam ac malesuada tortor, ut fermentum turpis. Cras posuere lacus eu blandit ultrices. Etiam eu finibus mi, eget viverra justo. Aenean ac neque et augue vestibulum eleifend sit amet eget turpis. Aenean eu nulla risus.Etiam ac scelerisque quam, et consequat urna. Nullam sit amet elementum justo. Cras fermentum luctus orci ac sollicitudin. Nulla semper tellus at leo finibus dictum. Vivamus tincidunt orci leo. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aenean aliquet, neque quis porta volutpat, augue nisi malesuada est, a porttitor libero elit sed turpis.Nunc ultricies sagittis tempus. Aliquam erat volutpat. Vestibulum pretium augue a eros tincidunt venenatis. Proin eu mauris mollis, vehicula purus id, venenatis sapien. Morbi in sagittis tortor. Ut laoreet, ex et rutrum posuere, est elit interdum nibh, quis finibus odio nibh at purus. Donec mattis, elit ac aliquet convallis, nibh lectus hendrerit lectus, in auctor nibh lectus at nunc. In ipsum nibh, pulvinar sit amet bibendum quis, facilisis in eros. Aliquam libero metus, faucibus nec ultrices vel, efficitur eget diam. Morbi ut urna malesuada, dapibus justo vitae, imperdiet est. Curabitur et odio a augue faucibus placerat et sit amet lectus. Ut tempor tellus at pharetra lacinia. Curabitur et leo ultrices, vestibulum odio in, malesuada diam. Proin ex ex, porttitor eget consectetur ac, pulvinar quis erat.Etiam id euismod metus. Quisque at diam arcu. Mauris semper porta erat id rutrum. Nunc sit amet felis sit amet dolor finibus venenatis. Mauris commodo quam nibh, sed euismod lectus egestas nec. Aliquam sit amet feugiat justo. Donec maximus placerat lectus et fringilla. Proin felis nibh, efficitur a lorem viverra, eleifend tempus nibh. Cras ac magna condimentum, dignissim felis eu, facilisis ante. Phasellus efficitur turpis et dolor imperdiet, vel gravida arcu sagittis. Vestibulum mollis ante eu eleifend aliquam. Etiam tincidunt viverra nisi id varius. Praesent non hendrerit turpis, id ultrices ligula. Nullam sed sapien mauris.",
    image: "/img/p7.png",
  },
  {
    id: 4,
    title: "item4",
    price: 640,
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas mollis ante et bibendum faucibus. Duis iaculis suscipit porta. Fusce commodo, felis sit amet ultrices vehicula, eros tellus vulputate turpis, sed consectetur libero dui tincidunt sem. Quisque mattis quam nisi, eget accumsan lectus finibus sed. Curabitur feugiat commodo elementum. Aliquam ac malesuada tortor, ut fermentum turpis. Cras posuere lacus eu blandit ultrices. Etiam eu finibus mi, eget viverra justo. Aenean ac neque et augue vestibulum eleifend sit amet eget turpis. Aenean eu nulla risus.Etiam ac scelerisque quam, et consequat urna. Nullam sit amet elementum justo. Cras fermentum luctus orci ac sollicitudin. Nulla semper tellus at leo finibus dictum. Vivamus tincidunt orci leo. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aenean aliquet, neque quis porta volutpat, augue nisi malesuada est, a porttitor libero elit sed turpis.Nunc ultricies sagittis tempus. Aliquam erat volutpat. Vestibulum pretium augue a eros tincidunt venenatis. Proin eu mauris mollis, vehicula purus id, venenatis sapien. Morbi in sagittis tortor. Ut laoreet, ex et rutrum posuere, est elit interdum nibh, quis finibus odio nibh at purus. Donec mattis, elit ac aliquet convallis, nibh lectus hendrerit lectus, in auctor nibh lectus at nunc. In ipsum nibh, pulvinar sit amet bibendum quis, facilisis in eros. Aliquam libero metus, faucibus nec ultrices vel, efficitur eget diam. Morbi ut urna malesuada, dapibus justo vitae, imperdiet est. Curabitur et odio a augue faucibus placerat et sit amet lectus. Ut tempor tellus at pharetra lacinia. Curabitur et leo ultrices, vestibulum odio in, malesuada diam. Proin ex ex, porttitor eget consectetur ac, pulvinar quis erat.Etiam id euismod metus. Quisque at diam arcu. Mauris semper porta erat id rutrum. Nunc sit amet felis sit amet dolor finibus venenatis. Mauris commodo quam nibh, sed euismod lectus egestas nec. Aliquam sit amet feugiat justo. Donec maximus placerat lectus et fringilla. Proin felis nibh, efficitur a lorem viverra, eleifend tempus nibh. Cras ac magna condimentum, dignissim felis eu, facilisis ante. Phasellus efficitur turpis et dolor imperdiet, vel gravida arcu sagittis. Vestibulum mollis ante eu eleifend aliquam. Etiam tincidunt viverra nisi id varius. Praesent non hendrerit turpis, id ultrices ligula. Nullam sed sapien mauris.",
    image: "/img/p8.png",
  },
];

export default Data;
